# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 10:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otc_type', models.CharField(blank=True, max_length=20)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        ),
    ]
