# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetimecode',
            old_name='fields',
            new_name='data',
        ),
    ]
