# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0002_auto_20170919_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='onetimecode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now()),
            preserve_default=False,
        ),
    ]
