# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('otc', '0003_auto_20170921_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
