# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region_name',
            field=models.CharField(default="default", max_length=50),
        ),
    ]
