# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_city_region_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
