# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('status', models.CharField(choices=[('KK', 'Unexpected problems'), ('KO', 'Not sent'), ('OK', 'Sent')], default='KO', max_length=2)),
                ('sent_log', models.TextField(null=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
