# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('OK', 'Sent'), ('KO', 'Not sent'), ('KK', 'Unexpected problems')], default='KO', max_length=2),
        ),
    ]
