# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='notification_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'about new feautures': True, 'about new orders in my city': True, 'when curier cancel my order': True, 'when customer approved me like a curier': True, 'when somebody comment me': True, 'when somebody take my order': True}),
        ),
    ]
