# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171031_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1, null=True),
        ),
    ]
