# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='type',
            field=models.CharField(choices=[('From', 'From'), ('To', 'To')], default='From', max_length=4),
        ),
    ]
