# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20171116_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_people_who_vote',
            field=models.IntegerField(default=0),
        ),
    ]
