# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171113_0935'),
        ('profiles', '0010_auto_20171116_1544'),
    ]

    operations = [
    ]
