# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 11:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_merge_20171120_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='share_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'about_me': True, 'birth_date': True, 'city': True, 'email': True, 'phone': True}),
        ),
    ]
