# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20171120_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sum_of_rating',
            field=models.IntegerField(default=0),
        ),
    ]
