# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 12:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cordinate_from', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('cordinate_to', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('delivery_price', models.IntegerField(blank=True, null=True)),
                ('order_price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_time', models.DateTimeField(blank=True, null=True)),
                ('to_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('active', 'active'), ('done', 'done'), ('finished', 'finished')], max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
