# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:14
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20171019_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cordinate_from',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'lat': 50.5210522, 'lng': 30.6215287}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cordinate_to',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'lat': 50.5210522, 'lng': 30.6215287}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='curier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
