# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20171023_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CandidatesList',
            new_name='Candidate',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='candidates',
            new_name='candidate',
        ),
    ]
