# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20171023_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='isChose',
            field=models.BooleanField(default=False),
        ),
    ]
