# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 12:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0009_candidate_ischose'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='waiting_for_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
