# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20171027_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waiting_for_candidate',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('public', 'public'), ('waiting_for_payment', 'waiting_for_payment'), ('active', 'active'), ('canceled', 'canceled'), ('done', 'done')], max_length=10),
        ),
    ]
