# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def generate_uuid(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for obj in Order.objects.all().iterator():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20171030_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(editable=False, max_length=32, null=True, verbose_name='UUID'),
            preserve_default=False,
        ),
        migrations.RunPython(
            generate_uuid,
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(editable=False, max_length=32, unique=True, verbose_name='UUID'),
            preserve_default=True,
        )
    ]
