# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20171101_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
