# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20171123_1225'),
        ('orders', '0018_auto_20171122_2006'),
    ]

    operations = [
    ]
