# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_merge_20171123_1634'),
        ('orders', '0021_merge_20171123_1646'),
    ]

    operations = [
    ]
