# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20171118_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
    ]
