# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('content', models.TextField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_curier', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
