# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20171116_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_from_curier', to=settings.AUTH_USER_MODEL),
        ),
    ]
