# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20171116_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
